### ISSUE TITLE
Confirm decimal places

### ISSUE THREAD

**Issue by jleni** [Zondax/ledger-polkadex#2]
Reference:
https://github.com/polkadot-js/common/blob/25196c336729b7259525f055e6e65a9bd8ed3ff7/packages/networks/src/substrate.ts#L552

But metadata returns 0

**Comment by arrudagates** [comment]
This is correct, you can confirm it in our customSpecRaw.json https://github.com/Polkadex-Substrate/Polkadex/releases/download/v1.0.7/customSpecRaw.json
