### ISSUE TITLE
Submit SLIP0044 registration

### ISSUE THREAD

**Issue by jleni** [Zondax/ledger-polkadex#3]
Related 
https://github.com/Zondax/ledger-substrate-js/releases/tag/v0.19.0

**Comment by jleni** [comment]
Reference:
https://github.com/satoshilabs/slips/blob/master/slip-0044.md

**Comment by jleni** [comment]
https://github.com/satoshilabs/slips/pull/801

**Comment by simonsso** [comment]
Something like this? 

https://github.com/satoshilabs/slips/pull/1216

Just pick a free number and add the symbol and url?

**Comment by jleni** [comment]
Yes, this PR is correct @simonsso
